version: 2.1

references:
  defaults: &defaults
    working_directory: ~/repo

orbs:
  slack: circleci/slack@0.1.10

executors:
  alpine_bash_curl_ssl:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps
  shellcheck:
    <<: *defaults
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6

commands:
  shellcheck:
    steps:
      - run:
          name: Analysis Script
          command: shellcheck .circleci/gen.sh
  generate_diary:
    steps:
      - run:
          name: Generate Base Diary
          command: /bin/bash .circleci/gen.sh
  configure_git:
    steps:
      - run:
          name: Configure Git
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 's+circleci@sugarshin.net'

jobs:
  analysis_script:
    executor:
      name: shellcheck
    steps:
      - checkout
      - shellcheck
  gen_diary:
    executor:
      name: alpine_bash_curl_ssl
    steps:
      - checkout
      - configure_git
      - generate_diary
  notify_slack:
    machine: true
    steps:
      - slack/notify:
          message: "Diary from commit ${CIRCLE_SHA1} ref: https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
          mentions: "${SLACK_UUID}"

workflows:
  scheduled_gen_diary:
    triggers:
      - schedule:
          # JST 23:00
          cron: "00 14 * * *"
          filters:
            branches:
              only: master
    jobs:
      - gen_diary
      - notify_slack:
         requires:
           - gen_diary
  test:
    jobs:
      - analysis_script:
          filters:
            branches:
              ignore: master
