version: 2.1

references:
  defaults: &defaults
    working_directory: ~/repo

orbs:
  slack: circleci/slack@0.1.10
  shellcheck: circleci/shellcheck@1.3.16

executors:
  buildpack_deps:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps
  # shellcheck:
  #   <<: *defaults
  #   docker:
  #     - image: nlknguyen/alpine-shellcheck:v0.4.6

commands:
  # shellcheck:
  #   steps:
  #     - run:
  #         name: Analysis Script
  #         command: shellcheck .circleci/gen.sh
  generate_diary:
    steps:
      - run:
          name: Generate Base Diary
          command: /bin/bash .circleci/gen.sh
  configure_git:
    steps:
      - run:
          name: Configure Git
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 's+circleci@sugarshin.net'

jobs:
  # analysis_script:
  #   executor:
  #     name: shellcheck
  #   steps:
  #     - checkout
  #     - shellcheck
  gen_diary:
    executor:
      name: buildpack_deps
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - e4:fe:4c:90:2b:1c:2d:40:89:3c:52:0c:0a:40:b2:07
      - configure_git
      - generate_diary
  notify_slack:
    machine: true
    steps:
      - slack/notify:
          message: "Diary from commit ${CIRCLE_SHA1} ref: https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
          mentions: "${SLACK_UUID}"

workflows:
  test:
    jobs:
      - shellcheck/check
  scheduled_gen_diary:
    triggers:
      - schedule:
          # JST 20:00
          cron: "00 11 * * *"
          filters:
            branches:
              only: master
    jobs:
      - shellcheck/check
      - gen_diary:
         requires:
           - shellcheck/check
      - notify_slack:
         requires:
           - gen_diary
  # test:
  #   jobs:
  #     - analysis_script:
  #         filters:
  #           branches:
  #             ignore: master
