version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.16

executors:
  buildpack_deps:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:stable

commands:
  generate_diary:
    steps:
      - run:
          name: Generate
          command: .circleci/gen.sh
  configure_git:
    steps:
      - run:
          name: Configure Git
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 's+circleci@sugarshin.net'
  install_git_and_ssh_client:
    steps:
      - run: |
          apk add --update-cache --no-progress \
            git \
            openssh-client

jobs:
  gen_diary:
    executor:
      name: buildpack_deps
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - e4:fe:4c:90:2b:1c:2d:40:89:3c:52:0c:0a:40:b2:07
      - configure_git
      - generate_diary

workflows:
  test:
    jobs:
      - shellcheck/check:
          pre-steps:
            - install_git_and_ssh_client
  scheduled_gen_diary:
    triggers:
      - schedule:
          # JST 06:00
          cron: "00 21 * * *"
          filters:
            branches:
              only: master
    jobs:
      - shellcheck/check:
          pre-steps:
            - install_git_and_ssh_client
      - gen_diary:
          requires:
            - shellcheck/check
